services:
    _defaults:
        public: false
        autowire: false
        autoconfigure: false

    ############################################################################
    # MIDDLEWARE                                                               #
    ############################################################################

    HBM\MessengerBundle\Messenger\Middleware\:
        resource: '../src/Messenger/Middleware'


    ############################################################################
    # HANDLER                                                                  #
    ############################################################################

    HBM\MessengerBundle\Messenger\Handler\:
        resource: '../src/Messenger/Handler'
        tags:
            - { name: messenger.message_handler }
