services:
    _defaults:
        public: false
        autowire: false
        autoconfigure: false

    ############################################################################
    # MIDDLEWARE                                                               #
    ############################################################################

    HBM\MessengerBundle\Messenger\Middleware\EmailThrottleMiddleware:
        arguments:
            $parameterBag: '@parameter_bag'

    ############################################################################
    # HANDLER                                                                  #
    ############################################################################

    HBM\MessengerBundle\Messenger\Handler\:
        resource: '../src/Messenger/Handler'
        tags:
            - { name: messenger.message_handler }
